name: Check count of tabs

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Save changed files in logfile
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "File $file have `grep '\t' Main.java | wc -l` tabs." > report.log 2>&1
          done
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: files_report.log
